import "./style/globals.scss";
import Head from "next/head";
import React from "react";
import BurgerMenu from "@/app/Components/BurgerMenu";
import Footer from "./Components/Footer/page";

export const metadata = {
  title: "Chloé Chartrain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Chloé Chartrain</title>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* à voir si besoin */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> */}

        {/* <!--* ne pas oublier les metadonnees--> */}
      </Head>
      <body>
        <BurgerMenu />
        {children}
        <Footer />
      </body>

    </html>
  );
}
