import "./globals.css";
import Head from "next/head";
import React from "react";

export const metadata = {
  title: "Chloé Chartrain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="fr">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Chloé Chartrain</title>
        <link rel="icon" href="/favicon.ico" sizes="any" />

        {/* <!--* ne pas oublier les metadonnees--> */}
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
